language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t vitor96k/react-app -f Dockerfile.dev .

script:
  - docker run -e CI=true vitor96k/react-app npm run test # Indicates that it's a CI process, so we should not wait for input data when running the tests

deploy:
  access_key_id: "$access_key"
  secret_access_key: "$secret_key"
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-502646121377"
  bucket_path: "docker-react"
  on:
    branch: master