language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t vitor96k/react-app -f Dockerfile.dev .

script:
  - docker run -e CI=true vitor96k/react-app npm run test # Indicates that it's a CI process, so we should not wait for input data when running the tests